### ISSUE TITLE
I'm having trouble with my nav

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/dsn1675-saas-website#1]
I wanted to make a toggle for the smallest screen, but I'm not sure if there's a class to make it so. The medium and large screens are what I wanted but it squishes too much when at the smallest size. Any suggestions? I already have all the classes where I want for medium and up, how would i turn it all to toggle?
@thomasjbradley

**Comment by thomasjbradley** [comment]
Check out the video and code samples here:
http://learn-the-web.algonquindesign.ca/topics/navigation/

**Comment by DizzyDez** [comment]
Yeah, I saw how to do that. But is there a way of doing it while keeping my grid styling intact?

**Comment by thomasjbradley** [comment]
Yep definitely, put all the toggle stuff inside the grid units you already have.
