### ISSUE TITLE
Tabbed box

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/dsn1675-saas-website#2]
When fixing my accessability, I noticed my focus box (when tabbing through my website) some of my links are rediculously oversized. it still works, it just makes it harder to click for some of them. Is there anyway I can fix this? Thanks, 
@thomasjbradley

**Comment by thomasjbradley** [comment]
It looks like it's caused the padding on the elements, specifically the `.island` classes.

**Comment by DizzyDez** [comment]
so is there another class I can put in place of island, that would use margin instead of padding?

**Comment by thomasjbradley** [comment]
Maybe try adding `display: inline-block` to them; padding doesn't work properly on `inline` elements, it causes the problem you're seeing.
