### ISSUE TITLE
My first image after my banner disappeared!

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/dsn1675-saas-website#4]
On my homepage, when I stretch down to my smallest size, My first image disappears to only a strip! I know its probably because there's no content and its a background image. But I used this &nbsp; element you showed me, and I'm not sure how to make it show the rest of my image! Small issue I know, but I've tried everything. 
@thomasjbradley

**Comment by thomasjbradley** [comment]
Maybe try adding a `min-height` to that `<div>` to force it to be at least a certain height.
