### ISSUE TITLE
This issue is with my pricing page

### ISSUE THREAD

**Issue by DizzyDez** [DizzyDez/dsn1675-saas-website#5]
It is laid out the same as the tour page, but with a great amount of text instead of images. Its the worst when at the largest size, because they are not aligned at all. I even changed the size of the text to make the blocks of texts relatively closer in size. Is there a way to vertically align these within the css I already have? 
@thomasjbradley

**Comment by thomasjbradley** [comment]
To start, I would say: remove the `.grid-middle` class and change it to `.grid-stretch`, that will align the tops.

Then using a combination of `.unit-content-distribute` and `.content-fill` you could also align the buttons. Check out the example on the cheat sheet here:
http://learn-the-web.algonquindesign.ca/topics/gridifier-cheat-sheet/#example-solutions

**Comment by DizzyDez** [comment]
That's exactly the attribute I needed. Alright, I've followed the example to the T, I must have missed something, because my "FREE" unit has moved way too far down. I found that the .island-2 attribute was applied to the others, but is that the proper way of making it look the way I want? Or is that too many attributes?

**Comment by thomasjbradley** [comment]
I think it's because of this inner `.grid`, here:
https://github.com/DizzyDez/dsn1675-saas-website/blob/gh-pages/pricing.html#L43

Deleting that, and getting rid of the unit classes might make a big difference.
